package com.settlekar.backend.enums;

public enum LedgerEntryType {
    GROUP_CREATED,
    MEMBER_JOINED,
    MEMBER_LEFT,
    EXPENSE_ADDED,
    EXPENSE_UPDATED,
    EXPENSE_DELETED,
    SETTLEMENT_CREATED,
    SETTLEMENT_COMPLETED,
    SETTLEMENT_FAILED,
    GROUP_LOCKED,
    GROUP_SETTLED,
    RECURRING_EXPENSE_GENERATED,
    REMINDER_SENT
}
